#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated file, don't edit!
 * Changes will be overwritten
 */

#define CPTCFG_WIRELESS 1
#define CPTCFG_NET_CORE 1
#define CPTCFG_EXPERT 1
#define CPTCFG_BT_MODULE 1
#define CPTCFG_BT_RFCOMM_MODULE 1
#define CPTCFG_BT_BNEP_MODULE 1
#define CPTCFG_BT_BNEP_MC_FILTER 1
#define CPTCFG_BT_BNEP_PROTO_FILTER 1
#define CPTCFG_BT_HIDP_MODULE 1
#define CPTCFG_BT_HCIBTUSB_MODULE 1
#define CPTCFG_BT_HCIBTSDIO_MODULE 1
#define CPTCFG_BT_HCIBCM203X_MODULE 1
#define CPTCFG_BT_HCIBPA10X_MODULE 1
#define CPTCFG_BT_HCIBFUSB_MODULE 1
#define CPTCFG_BT_HCIVHCI_MODULE 1
#define CPTCFG_BT_MRVL_MODULE 1
#define CPTCFG_BT_MRVL_SDIO_MODULE 1
#define CPTCFG_BT_ATH3K_MODULE 1
#define CPTCFG_BT_WILINK_MODULE 1
#define CPTCFG_WLAN 1
#define CPTCFG_WL_TI 1
#define CPTCFG_SSB_POSSIBLE 1
#define CPTCFG_BCMA_POSSIBLE 1
#define CPTCFG_BCMA_MODULE 1
#define CPTCFG_USB_WDM_MODULE 1
#endif /* COMPAT_AUTOCONF_INCLUDED */
